.job_template_deploy: &job_deploy
  type: deploy
  script:
  - helm --kube-context ric-sandbox upgrade $RELEASE_NAME $HELM_PATH
    --install
    --force
    --wait
    --namespace=$CI_PROJECT_NAMESPACE
    --set CI_PROJECT_NAME=$CI_PROJECT_NAME
    --set image.tag=$CI_COMMIT_TAG;
  except:
  - branches
